name: flutter_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  csc_picker: ^0.2.7
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/images/

flutter_native_splash:
  color: "#5BB7EE"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#5BB7EE"
  android: true
  ios: true
  web: false
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
