name: flutter_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  csc_picker: ^0.2.7
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  hive: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.0
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/images/
